# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bikesharingweb:
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik-azds  # Dev Spaces-specific
    hosts:
      - dev.bikesharingweb.q8spzqgspb.eus.azds.io  # Assumes deployment to the 'dev' space

gateway:
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik-azds  # Dev Spaces-specific
    hosts:
      - dev.gateway.q8spzqgspb.eus.azds.io  # Assumes deployment to the 'dev' space
