# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bikesharingweb:
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik-azds  # Dev Spaces-specific
    hosts:
      - dev.bikesharingweb.xsr88j86lf.eus.azdsstage.io  # Assumes deployment to the 'dev' space

gateway:
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik-azds  # Dev Spaces-specific
    hosts:
      - dev.gateway.xsr88j86lf.eus.azdsstage.io  # Assumes deployment to the 'dev' space