apiVersion: apps/v1
kind: Deployment
metadata:
    name: webfrontend-deployment
    labels:
        app: webfrontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webfrontend
  template:
    metadata:
      labels:
        app: webfrontend
    spec:
      containers:
      - name: webfrontend
        image: shicomimages.azurecr.io/webfrontend:v1
        ports:
        - containerPort: 80
