apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webfrontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: webfrontend
        image: __registryname__/__imagename__:__imagetag__
        imagePullPolicy: IfNotPresent


