apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mywebapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
        app: mywebapi
    spec:
      containers:
      - name: mywebapi
        image: __registryname__/__imagename__:__imagetag__
        imagePullPolicy: IfNotPresent