apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mywebapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: mywebapi
        image: __imagename__:__Build.BuildId__
        imagePullPolicy: IfNotPresent