kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/webfrontend
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: webfrontend
      tag: $(tag)
      pullPolicy: Never
    ingress:
      hosts:
      # This expands to [space.s.]dev.webfrontend.<guid>.<region>.aksapp.io
      - $(spacePrefix)dev.webfrontend$(hostSuffix)
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
    container:
      sync:
      - "**/**"
      iterate:
        processesToKill: [java]
        buildCommands:
        - [mvn, package, -Dmaven.test.skip=true, -Dcheckstyle.skip=true, -Dmaven.javadoc.skip=true]