{{ if .Values.hostedSql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "databases.fullname" . }}-sql
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: "4Gi"
{{ end }}