{{ if .Values.hostedSql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "databases.fullname" . }}-sql
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
    name: sql
  selector:
    app: {{ template "databases.fullname" . }}-sql
{{ end }}