# Default values for databases.
# This is a YAML-formatted file
# Declare variables to be passed into your templates.
fullnameOverride: databases
hostedSql:
  enabled: true
  password: "!DummyPassword123!"
hostedMongo:
  enabled: true