FROM microsoft/aspnetcore-build:2.0
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 80

WORKDIR /src
COPY mywebapi.csproj .
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
RUN dotnet build

CMD ["dotnet", "run", "--no-restore", "--no-build", "--no-launch-profile"]