name: Master

on:
  push:
    branches:
    - master
    paths:
    - samples/BikeSharingApp/**
    - "!**/*.md"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build samples/BikeSharingApp/Bikes/ -t ${{ secrets.CONTAINER_REGISTRY }}/bikes:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/bikes:$GITHUB_SHA
        
        docker build samples/BikeSharingApp/BikeSharingWeb/ -t ${{ secrets.CONTAINER_REGISTRY }}/bikesharingweb:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/bikesharingweb:$GITHUB_SHA
        
        docker build samples/BikeSharingApp/Billing/ -t ${{ secrets.CONTAINER_REGISTRY }}/billing:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/billing:$GITHUB_SHA
        
        docker build samples/BikeSharingApp/Gateway/ -t ${{ secrets.CONTAINER_REGISTRY }}/gateway:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/gateway:$GITHUB_SHA
        
        docker build samples/BikeSharingApp/Reservation/ -t ${{ secrets.CONTAINER_REGISTRY }}/reservation:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/reservation:$GITHUB_SHA
        
        docker build samples/BikeSharingApp/ReservationEngine/ -t ${{ secrets.CONTAINER_REGISTRY }}/reservationengine:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/reservationengine:$GITHUB_SHA
        
        docker build samples/BikeSharingApp/Users/ -t ${{ secrets.CONTAINER_REGISTRY }}/users:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/users:$GITHUB_SHA
      
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ${{ secrets.MASTER_SPACE }}
        container-registry-url: ${{ secrets.CONTAINER_REGISTRY }}
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: ${{ secrets.IMAGE_PULL_SECRET }}
      
    - uses: azure/k8s-bake@v1
      with:
          renderEngine: 'helm2'
          helmChart: './samples/BikeSharingApp/charts/'             
          helmVersion: 'v3.0.2'
          overrides: |             
            bikes.image.repository:${{ secrets.CONTAINER_REGISTRY }}/bikes
            bikes.image.tag:${{ github.sha }}
            bikes.imagePullSecrets[0].name:${{ secrets.IMAGE_PULL_SECRET }}
            bikesharingweb.image.repository:${{ secrets.CONTAINER_REGISTRY }}/bikesharingweb
            bikesharingweb.image.tag:${{ github.sha }}
            bikesharingweb.ingress.hosts[0]=${{ secrets.HOST }} \
            bikesharingweb.ingress.annotations.kubernetes\\.io/ingress\\.class=traefik-azds \
            bikesharingweb.imagePullSecrets[0].name:${{ secrets.IMAGE_PULL_SECRET }}
            billing.image.repository:${{ secrets.CONTAINER_REGISTRY }}/billing
            billing.image.tag:${{ github.sha }}
            billing.imagePullSecrets[0].name:${{ secrets.IMAGE_PULL_SECRET }}
            gateway.image.repository:${{ secrets.CONTAINER_REGISTRY }}/gateway
            gateway.image.tag:${{ github.sha }}
            gateway.imagePullSecrets[0].name:${{ secrets.IMAGE_PULL_SECRET }}
            gateway.ingress.hosts[0]=${{ secrets.GATEWAY_HOST }} \
            gateway.ingress.annotations.kubernetes\\.io/ingress\\.class=traefik-azds \
            reservation.image.repository:${{ secrets.CONTAINER_REGISTRY }}/reservation
            reservation.image.tag:${{ github.sha }}
            reservation.imagePullSecrets[0].name:${{ secrets.IMAGE_PULL_SECRET }}
            reservationengine.image.repository:${{ secrets.CONTAINER_REGISTRY }}/reservationengine
            reservationengine.image.tag:${{ github.sha }}
            reservationengine.imagePullSecrets[0].name:${{ secrets.IMAGE_PULL_SECRET }}
            users.image.repository:${{ secrets.CONTAINER_REGISTRY }}/users
            users.image.tag:${{ github.sha }}
            users.imagePullSecrets[0].name:${{ secrets.IMAGE_PULL_SECRET }}
      id: bake
      
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: ${{ steps.bake.outputs.manifestsBundle }}        
        imagepullsecrets: |
          ${{ secrets.IMAGE_PULL_SECRET }}
        namespace: ${{ secrets.MASTER_SPACE }}
